services:
  - type: web
    name: moa2004-smart-downloader
    runtime: docker
    repo: https://github.com/moa2004/smart-downloader
    branch: main
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: commit
    healthCheckPath: /api/tools
