services:
  - type: web
    name: smart-downloader
    runtime: docker
    repo: https://github.com/moa2004/smart-downloader
    branch: main
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    autoDeployTrigger: "off"
    healthCheckPath: /api/tools
